package com.giadinh.apporderbill.shared.error;

import org.springframework.http.HttpStatus;

/**
 * Stable machine-readable error codes for domain rules and API responses.
 */
public enum ErrorCode {

    ORDER_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORDER_MENU_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORDER_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORDER_NOT_MODIFIABLE(HttpStatus.CONFLICT),
    ORDER_NEW_TABLE_ID_REQUIRED(HttpStatus.BAD_REQUEST),
    ORDER_ITEM_QUANTITY_INVALID(HttpStatus.BAD_REQUEST),

    TABLE_NOT_AVAILABLE_FOR_ASSIGN(HttpStatus.CONFLICT),
    TABLE_ID_REQUIRED(HttpStatus.BAD_REQUEST),
    TABLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    SOURCE_TABLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    TARGET_TABLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    SOURCE_TABLE_NO_ACTIVE_ORDER(HttpStatus.CONFLICT),
    TARGET_TABLE_NOT_EMPTY(HttpStatus.CONFLICT),

    TABLE_NUMBER_REQUIRED(HttpStatus.BAD_REQUEST),
    NO_ACTIVE_ORDER_FOR_TABLE(HttpStatus.NOT_FOUND),
    ORDER_HAS_ITEMS_CANNOT_RELEASE(HttpStatus.CONFLICT),

    TRANSFER_SOURCE_TABLE_NAME_REQUIRED(HttpStatus.BAD_REQUEST),
    TRANSFER_TARGET_TABLE_NAME_REQUIRED(HttpStatus.BAD_REQUEST),
    TRANSFER_SAME_SOURCE_AND_TARGET_TABLE(HttpStatus.BAD_REQUEST),

    TABLE_DISPLAY_NAME_REQUIRED(HttpStatus.BAD_REQUEST),
    RENAME_TABLE_ACTIVE_ORDER_EXISTS(HttpStatus.CONFLICT),
    TABLE_NAME_DUPLICATE(HttpStatus.CONFLICT),
    TABLE_ADD_NAME_INVALID(HttpStatus.BAD_REQUEST),

    TABLE_RESERVATION_BLOCKED_BY_ACTIVE_ORDER(HttpStatus.CONFLICT),
    TABLE_RESERVATION_BLOCKED_BY_LINKED_ORDER(HttpStatus.CONFLICT),
    TABLE_RESERVATION_OCCUPIED_CANNOT_RESERVE(HttpStatus.CONFLICT),
    TABLE_NOT_IN_RESERVED_STATE(HttpStatus.BAD_REQUEST),

    CHECKOUT_ORDER_ID_REQUIRED(HttpStatus.BAD_REQUEST),
    CHECKOUT_ORDER_NOT_PAYABLE_STATE(HttpStatus.CONFLICT),
    CHECKOUT_PAID_AMOUNT_INSUFFICIENT(HttpStatus.BAD_REQUEST),

    KITCHEN_ORDER_ID_REQUIRED(HttpStatus.BAD_REQUEST),
    PRINTER_KITCHEN_SEND_FAILED(HttpStatus.SERVICE_UNAVAILABLE),
    PRINTER_RECEIPT_SEND_FAILED(HttpStatus.SERVICE_UNAVAILABLE),
    PRINT_RECEIPT_PAYMENT_ID_REQUIRED(HttpStatus.BAD_REQUEST),

    MENU_IMPORT_EXCEL_NOT_CONFIGURED(HttpStatus.INTERNAL_SERVER_ERROR),

    KITCHEN_SELECTED_ITEMS_REQUIRED(HttpStatus.BAD_REQUEST),
    KITCHEN_NO_ITEMS_TO_PRINT(HttpStatus.BAD_REQUEST),
    KITCHEN_ORDER_NO_ITEMS_FOR_TICKET(HttpStatus.BAD_REQUEST),

    BILL_NOT_FOUND(HttpStatus.NOT_FOUND),
    BILL_TOTAL_INVALID(HttpStatus.BAD_REQUEST),
    BILL_PAYMENT_AMOUNT_INVALID(HttpStatus.BAD_REQUEST),
    BILL_ALREADY_PAID(HttpStatus.CONFLICT),
    BILL_PAYMENT_STATE_INVALID(HttpStatus.CONFLICT),

    MENU_ITEM_NAME_REQUIRED(HttpStatus.BAD_REQUEST),
    MENU_ITEM_PRICE_INVALID(HttpStatus.BAD_REQUEST),
    MENU_ITEM_CATEGORY_REQUIRED(HttpStatus.BAD_REQUEST),
    MENU_ITEM_STOCK_LEVELS_INVALID(HttpStatus.BAD_REQUEST),
    MENU_ITEM_STOCK_CURRENT_INVALID(HttpStatus.BAD_REQUEST),
    MENU_ITEM_CANNOT_ACTIVATE_OUT_OF_STOCK(HttpStatus.CONFLICT),
    MENU_ITEM_STOCK_NOT_TRACKED(HttpStatus.CONFLICT),
    MENU_ITEM_STOCK_DECREASE_INVALID(HttpStatus.BAD_REQUEST),
    MENU_ITEM_STOCK_INSUFFICIENT(HttpStatus.CONFLICT),
    MENU_ITEM_STOCK_INCREASE_INVALID(HttpStatus.BAD_REQUEST),

    CATEGORY_NAME_REQUIRED(HttpStatus.BAD_REQUEST),

    CUSTOMER_PHONE_REQUIRED(HttpStatus.BAD_REQUEST),
    CUSTOMER_PHONE_DUPLICATE(HttpStatus.CONFLICT),
    CUSTOMER_NOT_FOUND(HttpStatus.NOT_FOUND),
    CUSTOMER_INSUFFICIENT_POINTS(HttpStatus.BAD_REQUEST),

    ROLE_NAME_REQUIRED(HttpStatus.BAD_REQUEST),
    PERMISSION_NAME_REQUIRED(HttpStatus.BAD_REQUEST),

    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    AUTH_FORBIDDEN(HttpStatus.FORBIDDEN),
    USER_ROLE_GROUP_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_USERNAME_DUPLICATE(HttpStatus.CONFLICT),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    ROLE_GROUP_NOT_FOUND(HttpStatus.NOT_FOUND),
    ROLE_GROUP_NAME_DUPLICATE(HttpStatus.CONFLICT),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND),
    CATEGORY_NAME_DUPLICATE(HttpStatus.CONFLICT),
    MENU_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND),
    MENU_ITEM_NAME_DUPLICATE(HttpStatus.CONFLICT),
    MENU_ITEM_STOCK_OPERATION_INVALID(HttpStatus.BAD_REQUEST),
    IDENTITY_FUNCTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    PERMISSION_ASSIGNMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PERMISSION_ASSIGNMENT_DUPLICATE(HttpStatus.CONFLICT),

    SQLITE_CONNECTION_NOT_CONFIGURED(HttpStatus.INTERNAL_SERVER_ERROR),

    COMMON_VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }

    public String code() {
        return name();
    }
}
